language: node_js
sudo: false
cache: yarn
node_js: lts/*
after_success:
- yarn test
script:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
#env:
#  global:
    secure: $FIREBASE_TOKEN