language: node_js
sudo: false
cache: yarn
node_js: lts/*
after_success:
- yarn test
script:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
#env:
#  global:
    secure: 22GQObx5v1aPA3Mgky9+7A6u0NPeYqN0vJvm0/MWWWc/t3RJrt2NDBLVc/7dyOt4dEcuxYs3DJUF/SznvZXrZAXeT9mdcI9djYca4JUAfQNopZ6FMF//VCxCTx+CkWuVcjZrtL7Ni994/B+tIMxfYYMA5vvvKvOxJjjULs0oSf/PhrrgrA56m1VyY45NTfpzDn/RIOOLh9qb91D1hwC051mjigLck2Nidht9AR90QF5nWN4lqV5Kd9Lbw/jHJpdWtV3Lnt0JXnZIEFBZQSq+1fW8gBYFd7wm1fFMv4JCqB70pq8JUKnh2/ZfgXduy3EDRL1+3I4hn8LdeKZNxmzNCc0Xstxv/HRMOTCR/k8EP/n0N/yy8Cx7egIPDXX+utw8c19+onNl865j84iYaR0+l+Oh3ntoTfypTzjaZ9hGvE+uMB6YH7+352TfYg8vXXaCjW0WhGLredXGeF1coIIcb/bOczTPdT/+gxl7vrXclB1HTTJ6TJlqEu3WFnrY1ouhwqqXR2+6g7HotOCq2v0ljCnLHXEf7Erx+KpCGzptjQqyWW7KweKMtZ63D1F7v3avAZZCszzh01TF/1lRZzWCs7SO1P8CxhVWhp0lw/KItyUo7ezZkQS/4+SBQ0pufxvd57Iqm8VrmR1W6sT2fsOZaWc9tZZTjvAhpCEoYEIBlyc=
